### ISSUE TITLE
详细文档挂了

### ISSUE THREAD

**Issue by babizhu** [anwenhu/zhixuewang-python#16]
详细文档挂了，打开404

**Comment by woshixiaofu666** [comment]
+1

**Comment by xingjian-xu** [comment]
++

**Comment by anwenhu** [comment]
感谢反馈， 但目前文档还未完善，短时间内无法放出.  不过源码里都有注释的, 如果想弄清的话可以直接看源码注释的

**Comment by anwenhu** [comment]
现在可以查看[Wiki](https://github.com/anwenhu/zhixuewang/wiki/Home/)了

**Comment by MasterYuan418** [comment]
请移步：https://zxdoc.risconn.com
