### ISSUE TITLE
API失效，获取成绩与考试列表出错

### ISSUE THREAD

**Issue by SherkeyXD** [anwenhu/zhixuewang-python#29]
考试列表
![image](https://user-images.githubusercontent.com/57581480/99484221-e0e8fd00-299a-11eb-9f61-da525f33c773.png)
成绩
![image](https://user-images.githubusercontent.com/57581480/99484870-3d005100-299c-11eb-82fc-6beb5e72ff0f.png)

**Comment by SherkeyXD** [comment]
似乎是智学网关闭了api接口？

**Comment by aquamarine5** [comment]
https://github.com/anwenhu/zhixuewang-python/pull/32
我修复了考试列表 获取成绩暂未测试

**Comment by SherkeyXD** [comment]
> #32
> 我修复了考试列表 获取成绩暂未测试

已经可以获取考试列表与成绩， 可以把更改合并了
顺带 zhixuewang/models.py 中228行chemisry应改为chemistry
